title: "Portafolio de Ingeniería"
description: "Mecatrónica y Control Inteligente | Estefania Cruz"

# GitHub Pages
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# URL (IMPORTANTE que coincida con tu repo)
url: "https://StagedFall846.github.io"
baseurl: "/portafolio-just-the-docs"

# 🌙 MODO OSCURO 
color_scheme: light
syntax_highlighter: rouge

# Just the Docs config
just_the_docs:
  custom_css:
    - "assets/css/custom.css"
  footer_content: "Estefania Cruz Fragoso"

search_enabled: true
search:
  heading_level: 2

# Links
aux_links:
  "Mi GitHub":
    - "https://github.com/StagedFall846"

# Permalinks
permalink: pretty

# Excluir archivos
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
